[package]
name = "space-game-bimensal"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]

[dependencies]
dubble = "0.1.0"
three = "0.3.1"
mint = "0.5.0"
cgmath = "0.16.1"
kiss3d = "0.16.3"
na = "0.16.0"
